### ISSUE TITLE
covins咨询

### ISSUE THREAD

**Issue by yonggaogit** [pengllbit/lio-sam#1]

**Comment by pengllbit** [comment]
这个问题是初始化不成功，主要在于硬件和标定，D435i自带imu噪声比较大影响很大，例如vins的作者都是用大疆飞控上的imu，然后需要一个比较精准的外参。最终我用D435i完成了初始化，你可以尝试改变这个参数 config_comm.yaml中的orb.imu_stamp_max_diff: 2.0，我忘记改成1.0还是多少了，然后在一个特征点非常丰富的环境，不跟丢的情况下，尽可能给imu大的激励，就完成了初始化。

**Comment by yonggaogit** [comment]
> 



> 这个问题是初始化不成功，主要在于硬件和标定，D435i自带imu噪声比较大影响很大，例如vins的作者都是用大疆飞控上的imu，然后需要一个比较精准的外参。最终我用D435i完成了初始化，你可以尝试改变这个参数 config_comm.yaml中的orb.imu_stamp_max_diff: 2.0，我忘记改成1.0还是多少了，然后在一个特征点非常丰富的环境，不跟丢的情况下，尽可能给imu大的激励，就完成了初始化。

好的，谢谢！按您说的试了一下还是不行，能和您再具体交流一下吗，能留一下您的邮箱吗，我的邮箱：220212031@seu.edu.cn

**Comment by pengllbit** [comment]
我的邮箱pengll_heu@163.com
